backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $this->view->title='Dashboard';
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use common\models\Program;
use common\models\Banner;
use common\models\Config;
use common\models\News;
use common\models\Member;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        $this->view->title = Config::findOne(['key_config'=>'g_title'])->value;
        $banner=Banner::find()
                ->where(['configuration_type'=>1])
                ->orWhere(['configuration_type'=>3])
                ->orderBy(['order_banner'=>SORT_ASC])
                ->all();
        $program=Program::find()
                ->where(['display_status'=>1])
                ->orderBy(['order_program'=>SORT_ASC])
                ->all();
        $caption=Config::findOne(['key_config'=>'brd_caption']);
        $news=News::find()
              ->where(['display_status'=>1])
              ->orderBy(['date_created'=>SORT_DESC])
              ->limit(6)
              ->all();


        return $this->render('index',[
                'banner'=>$banner,
                'program'=>$program,
                'caption'=>$caption,
                'news'=>$news,
            ]);
    }

    public function actionFunlabs()
    {
        $this->view->title = Config::findOne(['key_config'=>'g_title'])->value;

        $banner=Banner::find()
        ->where(['configuration_type'=>1])
        ->orWhere(['configuration_type'=>8])
        ->orderBy(['order_banner'=>SORT_ASC])
        ->all();
        $caption=Config::findOne(['key_config'=>'flb_caption']);
        $logo=Config::findOne(['key_config'=>'flb_logo']);
        $address=Config::findOne(['key_config'=>'flb_address']);
        return $this->render('funlabs',[
                'banner'=>$banner,
                'caption'=>$caption,
                'logo'=>$logo,
                'address'=>$address,
            ]);

    }

    public function actionNewsletterpost()
    {
        $newsletter=new \common\models\NewsLetter();
        $newsletter->name=$_POST['name'];
        $newsletter->email=$_POST['email'];
        $newsletter->save();
        Yii::$app->session->setFlash('success', "Terimakasih telah berpartisipasi!");
        return $this->redirect(\Yii::$app->request->referrer);



    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending your message.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionAbout()
    {
        $this->view->title = Config::findOne(['key_config'=>'g_title'])->value.' | Budaya';

        $banner=Banner::find()
                ->where(['configuration_type'=>1])
                ->orWhere(['configuration_type'=>2])
                ->orderBy(['order_banner'=>SORT_ASC])
                ->all();

        $caption=Config::findOne(['key_config'=>'bdy_caption']);
        $content1_title=Config::find()
                ->where(['key_config'=>'bdy_content1_title'])
                ->one();
        $content1_text=Config::find()
                ->where(['key_config'=>'bdy_content1_text'])
                ->one();

        $content2_title=Config::find()
                ->where(['key_config'=>'bdy_content2_title'])
                ->one();
        $content2_text=Config::find()
                ->where(['key_config'=>'bdy_content2_text'])
                ->one();

        $content3_title=Config::find()
                ->where(['key_config'=>'bdy_content3_title'])
                ->one();
        $content3_text=Config::find()
                ->where(['key_config'=>'bdy_content3_text'])
                ->one();
        $content4_title=Config::find()
                ->where(['key_config'=>'bdy_content4_title'])
                ->one();
        $content4_text=Config::find()
                ->where(['key_config'=>'bdy_content4_text'])
                ->one();

        return $this->render('about',[
            'banner'=>$banner,
            'caption'=>$caption,
            'content1_title'=>$content1_title,
            'content1_text'=>$content1_text,
            'content2_title'=>$content2_title,
            'content2_text'=>$content2_text,
            'content3_title'=>$content3_title,
            'content3_text'=>$content3_text,
            'content4_title'=>$content4_title,
            'content4_text'=>$content4_text,
            ]);
    }

    public function actionTimKami()
    {
         $this->view->title = Config::findOne(['key_config'=>'g_title'])->value.' | Tim Kami';
         $banner=Banner::find()
         ->where(['configuration_type'=>1])
         ->orWhere(['configuration_type'=>4])
         ->orderBy(['order_banner'=>SORT_ASC])
         ->all();
         $content_title=Config::find()
                ->where(['key_config'=>'tk_content_title'])
                ->one();
         $content_text=Config::find()
                ->where(['key_config'=>'tk_content_text'])
                ->one();
         $caption=Config::findOne(['key_config'=>'tk_caption']);


         $team=Member::find()
                ->where(['status'=>1])
                ->all();
         return $this->render('tim_kami',[
            'banner'=>$banner,
            'caption'=>$caption,
            'content_title'=>$content_title,
            'content_text'=>$content_text,
            'team'=>$team,
            ]);

    }

    public function actionPartner()
    {
       $this->view->title = Config::findOne(['key_config'=>'g_title'])->value.' | Partner';
       $banner=Banner::find()
       ->where(['configuration_type'=>1])
       ->orWhere(['configuration_type'=>5])
       ->orderBy(['order_banner'=>SORT_ASC])
       ->all();
        $volunteer=Member::find()
                ->where(['status'=>2])
                ->all();
        $caption=Config::findOne(['key_config'=>'pt_caption']);
        $content_title=Config::find()
                ->where(['key_config'=>'pt_content_title'])
                ->one();
        $content_text=Config::find()
                ->where(['key_config'=>'pt_content_text'])
                ->one();

        return $this->render('volunteer',[
            'banner'=>$banner,
            'caption'=>$caption,
            'content_title'=>$content_title,
            'content_text'=>$content_text,
            'volunteer'=>$volunteer,
            ]);


    }

    public function actionPublikasi()
    {
        $this->view->title = Config::findOne(['key_config'=>'g_title'])->value.' | Publikasi';
       $banner=Banner::find()
       ->where(['configuration_type'=>1])
       ->orWhere(['configuration_type'=>6])
       ->orderBy(['order_banner'=>SORT_ASC])
       ->all();
        $caption=Config::findOne(['key_config'=>'pub_caption']);
        $content_title=Config::find()
                ->where(['key_config'=>'pub_content_title'])
                ->one();
        $news=News::find()
                ->where(['display_status'=>1])
                ->orderBy(['date_created'=>SORT_DESC])
                ->all();

        return $this->render('publikasi',[
            'banner'=>$banner,
            'caption'=>$caption,

frontend/views/site/_about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>This is the About page. You may modify the following file to customize its content:</p>

    <code><?= __FILE__ ?></code>
</div>

frontend/views/site/about.php
<div style="overflow:hidden;">
<div id="header">
    <header class="header" style="position: relative;"><!--header-start-->
      <div id="bg-opacity-header" style="position: absolute;width: 100%;height: 100%;background-color: rgba(0, 0, 0, 0.7);z-index: 1; "></div>
      <div class="container-fluid img-opacity-header" style="height: 100%; width: 100%;">
            <div id="myCarousel" class="carousel slide" data-ride="carousel" style="height: 90vh; width: 100%;">
  			<!-- Indicators -->
  			<ol class="carousel-indicators">
  			   <?php 
                    foreach ($banner as $key => $bn) {
                 ?>
                    <?php if($key==0){?>
                        <li data-target="#myCarousel" data-slide-to="<?php echo $key; ?>" class="active"></li>
                    <?php }else{?>
                        <li data-target="#myCarousel" data-slide-to="<?php echo $key; ?>"></li>
                    <?php } ?>

                 <?php } ?>
  			</ol>

  			<!-- Wrapper for slides -->
  			<div class="carousel-inner" role="listbox" style="height: 100%; width: 100%;">

  			  <?php 
                    foreach ($banner as $key => $bn) {
                 ?>
                    <?php if($key==0){?>
                     <div class="item active">
                        <img src="<?=Yii::$app->urlManager->createUrl('/uploads/'.$bn->image)?>" alt="">
                    </div>
                    <?php }else{?>
                    <div class="item">
                        <img src="<?=Yii::$app->urlManager->createUrl('/uploads/'.$bn->image)?>" alt="">
                    </div>      
                    <?php } ?>

                 <?php } ?>
  		  
  			</div>
  		  </div>		  
    </div>
    <div>
      <div class="caption">
      <?php echo $caption->value; ?>
      </div>
    </div>
	</header><!--header-end-->
</div>

<section class="main-section" id="service"><!--main-section-start-->
	<div class="container">
    	<h2 class="text-padding-h2 wow fadeInUp delay-02s text-orange"><?php echo $content1_title->value; ?></h2>
		<h6 class="text-padding-h2 wow fadeInUp delay-04s text-black">
      <?php echo $content1_text->value; ?>
    </h6>
		<br>
		<div class="col-md-6 col-xs-6 no-padding-left">
			<h3 class="text-padding-h2 wow fadeInUp delay-06s text-orange"><?php echo $content2_title->value; ?></h3>
      <small class="text-padding-h2 wow fadeInUp delay-08s text-black"><?php echo $content2_text->value; ?></small>     
		</div>
		<div class="col-md-6 col-xs-6 no-padding-right">
			<h3 class="text-padding-h2 wow fadeInUp delay-1s text-orange"><?php echo $content3_title->value; ?></h3>
			<small class="text-padding-h2 wow fadeInUp delay-12s text-black"><?php echo $content3_text->value; ?></small>		
		</div>		
	</div>
</section><!--main-section-end-->


<section class="main-section paddind" id="Portfolio">
	<div class="container">
		<h2 class="text-padding-h2 wow fadeInUp delay-02s text-white"><?php echo $content4_title->value; ?></h2>
    <div id="about-bottom-icon">
	     <?php echo $content4_text->value; ?>
	  </div>
  </div>
</section>

frontend/views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.
    </p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'email') ?>

                <?= $form->field($model, 'subject') ?>

                <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                    'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                ]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>

</div>

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

frontend/views/site/funlabs.php
<div style="overflow:hidden;">
<header class="header" id="header"><!--header-start-->
	<div class="container">
		<div class="col-md-5 col-xs-5 no-padding-left" align="left">
			<?php echo $caption->value; ?>
		</div>
		<div class="col-md-7 col-xs-7 no-padding-right" align="right">
			<img src="<?=Yii::$app->urlManager->createUrl('/uploads/'.$logo->value)?>" style="padding: 100px 0;"/>
		</div>
    </div>
</div>
</header><!--header-end-->

<section class="main-section team" id="team"><!--main-section team-start-->
	<div class="container">
		  <div id="myCarousel" class="carousel slide" data-ride="carousel">
			<!-- Indicators -->
			<ol class="carousel-indicators">
			  <?php
                    foreach ($banner as $key => $bn) {
                 ?>
                    <?php if($key==0){?>
                        <li data-target="#myCarousel" data-slide-to="<?php echo $key; ?>" class="active"></li>
                    <?php }else{?>
                        <li data-target="#myCarousel" data-slide-to="<?php echo $key; ?>"></li>
                    <?php } ?>

                 <?php } ?>
			</ol>

			<!-- Wrapper for slides -->
			<div class="carousel-inner" role="listbox">

			  <?php
                    foreach ($banner as $key => $bn) {
                 ?>
                    <?php if($key==0){?>
                     <div class="item active">
                        <img src="<?=Yii::$app->urlManager->createUrl('/uploads/'.$bn->image)?>" alt="">
                    </div>
                    <?php }else{?>
                    <div class="item">
                        <img src="<?=Yii::$app->urlManager->createUrl('/uploads/'.$bn->image)?>" alt="">
                    </div>
                    <?php } ?>

                 <?php } ?>

			</div>

			<!-- Left and right controls -->
			<a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
			  <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
			  <span class="sr-only">Previous</span>
			</a>
			<a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
			  <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
			  <span class="sr-only">Next</span>
			</a>
		  </div>

			<br>
			<!-- <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3981.9017096138655!2d98.64684351387037!3d3.609961351155771!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x30312e1009d1848d%3A0x36c91b8ae9a75bf8!2sJl.+Pembangunan+No.40%2C+Helvetia+Tim.%2C+Medan+Helvetia%2C+Kota+Medan%2C+Sumatera+Utara+20117!5e0!3m2!1sen!2sid!4v1481862555550" width="1140" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>		   -->
			<iframe id="funlabs-maps" src="https://www.google.com/maps/embed/v1/place?key=AIzaSyDEJifTz-2J9QyeCN9F45uNcSozkeLqSaI&q=<?php echo $address->value; ?>" width="1140" height="450" frameborder="0" style="border:0; width: 100%;" allowfullscreen></iframe>
    </div>
</section><!--main-section team-end-->

frontend/views/site/index.php
<?php

/* @var $this yii\web\View */

?>


<div id="header">
    <header class="header" style="position: relative;"><!--header-start-->
      <div id="bg-opacity-header" style="position: absolute;width: 100%;height: 100%;background-color: rgba(0, 0, 0, 0.7);z-index: 1; "></div>
      <div class="container-fluid img-opacity-header" style="height: 100%; width: 100%;">
            <div id="myCarousel" class="carousel slide" data-ride="carousel" style="height: 90vh; width: 100%;">
              <!-- Indicators -->
              <ol class="carousel-indicators">
                <?php 
                      foreach ($banner as $key => $bn) {
                   ?>
                      <?php if($key==0){?>
                          <li data-target="#myCarousel" data-slide-to="<?php echo $key; ?>" class="active"></li>
                      <?php }else{?>
                          <li data-target="#myCarousel" data-slide-to="<?php echo $key; ?>"></li>
                      <?php } ?>

                   <?php } ?>
              </ol>

              <!-- Wrapper for slides -->
              <div class="carousel-inner" role="listbox" style="height: 100%; width: 100%;">

                  <?php 
                      foreach ($banner as $key => $bn) {
                   ?>
                      <?php if($key==0){?>
                       <div class="item active">
                          <img src="<?=Yii::$app->urlManager->createUrl('/uploads/'.$bn->image)?>" alt="">
                      </div>
                      <?php }else{?>
                      <div class="item">
                          <img src="<?=Yii::$app->urlManager->createUrl('/uploads/'.$bn->image)?>" alt="">
                      </div>      
                      <?php } ?>

                   <?php } ?>
                

                <!-- 
              
                <div class="item">
                  <img src="img/img_chania3.jpg" alt="Flower">
                </div>

                <div class="item">
                  <img src="img/img_chania4.jpg" alt="Flower">
                </div> -->
            
              </div>
            </div>          
      </div>
      <div>
        <div class="caption">
            <?php echo $caption->value; ?>
        </div>
        <div class="btn-caption"><a href="#">DAFTAR</a></div>
      </div>
    </header><!--header-end-->
</div>

<section class="main-section menu-item" id="team"><!--main-section team-start-->
    <div class="container">
        <div class="team-leader-block">
            <div class="row">
            <?php foreach ($program as $key => $prog) {?>
              <div class="col-md-3 col-xs-12">
                <div class="row" style="margin-bottom: 20px;">
                  <div class="col-md-12 col-xs-4 wow fadeInDown delay-03s"> 
                      <img src="<?=Yii::$app->urlManager->createUrl('/uploads/'.$prog->image)?>" alt="">
                  </div>
                  <div class="col-md-12 col-xs-8">
                    <h3 class="wow fadeInDown delay-03s"><?php echo $prog->name; ?></h3>
                    <p class="wow fadeInDown delay-03s">
                          <?php echo $prog->description; ?>
                    </p>
                  </div>
                </div>                 
              </div>
            <?php } ?>
            </div>
            
        </div>
    </div>
</section><!--main-section team-end-->


<section class="main-section story" id="Portfolio"><!--main-section-start-->
    <div class="container">
    <h2 class="text-padding-h2 text-orange wow fadeInUp delay-02s">Cerita Kami</h2> 
        <?php foreach ($news as $key => $nws) {?>
            <?php $image=Yii::$app->urlManager->createUrl('/uploads/'.$nws->banner_image); ?>
            <div class="col-md-4 col-xs-12 no-padding-left">
            <a href="<?php echo \Yii::$app->urlManager->createUrl('news/'.$nws->id.'/'.$nws->title); ?>"><div class="image-photo bg-photo-1" style="background:url('<?php echo $image; ?>')"></div></a>
            <h3 class="text-black text-capitalize"><?php echo $nws->title; ?></h3>
            <h6 class="text-black text-capitalize text-left">Oleh : <?php echo $nws->writer; ?></h6>
            <!-- <i class="fa fa-facebook fa-fb" aria-hidden="true"></i>
            <i class="fa fa-twitter fa-tw" aria-hidden="true"></i>
            <i class="fa fa-whatsapp fa-wa" aria-hidden="true"></i>
            <i class="fa fa-pinterest fa-pin" aria-hidden="true"></i>
            <i class="fa fa-envelope" aria-hidden="true"></i> -->
            <?php if(($key+1)%3==0){ ?>
                <div class="clearfix"></div> <br/><br/><br/>
            <?php } ?>
        </div>

        <?php } ?>
    </div>
</section>

<section class="main-section alabaster" id="alabaster"><!--main-section-start-->
    <div class="container">

    <h4 class="text-padding-h2 text-white text-center wow fadeInUp delay-02s">ingin mendapatkan cerita atau kegiatan inspiratif lainnya ?</h4>  
    <?= \yii\helpers\Html::beginForm(['site/newsletterpost'], 'post', ['enctype' => 'multipart/form-data']) ?>
    <div class="form-group">
      <input type="text" class="form-control input-transparent" id="usr" name='name' placeholder="Nama Kamu">
    </div>
    <div class="form-group">
      <input type="text" class="form-control input-transparent" id="mail" name='email' placeholder="Email">
    </div>  
    <div align="right"><button type="submit" class="btn btn-warning btn-to-left">Daftar</button></div>
    <?= \yii\helpers\Html::endForm() ?>
        
    </div>
</section>

frontend/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>

                <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'password')->passwordInput() ?>

                <?= $form->field($model, 'rememberMe')->checkbox() ?>

                <div style="color:#999;margin:1em 0">
                    If you forgot your password you can <?= Html::a('reset it', ['site/request-password-reset']) ?>.
                </div>

                <div class="form-group">
                    <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/requestPasswordResetToken.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\PasswordResetRequestForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Request password reset';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-request-password-reset">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out your email. A link to reset password will be sent there.</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'request-password-reset-form']); ?>

                <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Send', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/resetPassword.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ResetPasswordForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Reset password';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-reset-password">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please choose your new password:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'reset-password-form']); ?>

                <?= $form->field($model, 'password')->passwordInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Save', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>